# Generated by Django 3.2.7 on 2023-08-29 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('amount', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum amount of mateerials 1')])),
                ('availability', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('doors_windows', 'Doors and Windows'), ('construction_materials', 'Construction Materials'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
    ]
