# Generated by Django 3.2.7 on 2023-08-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('doors', 'Doors'), ('windows', 'Windows'), ('bricks', 'Bricks'), ('blocks', 'Blocks'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
